### ISSUE TITLE
Error: Cannot find module 'snoostorm' after upgrading to 1.2.0

### ISSUE THREAD

**Issue by jasonharrison** [MayorMonty/Snoostorm#24]
**Describe the bug**

Cannot find module 'snoostorm' after upgrading to snoostorm@1.2.0.

**To Reproduce**

```bash
mkdir tmp/ && cd tmp/
yarn add snoostorm
echo "require('snoostorm')" > blah.js
node blah.js
```

**Expected behavior**

The snoostorm module should be imported.

**Observed behavior**

```bash
jason@phl07s26 ~/projects/snoostorm> mkdir tmp/ && cd tmp/
                       yarn add snoostorm
                       echo "require('snoostorm')" > blah.js
                       node blah.js
yarn add v1.17.3
...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
...
success Saved 1 new dependency.
info Direct dependencies
└─ snoostorm@1.2.0
info All dependencies
└─ snoostorm@1.2.0
Done in 1.53s.

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'snoostorm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/jason/projects/test/tmp/blah.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```

**System Configuration:**
Using TypeScript?  **Fails for both TS and nodeJS.** 
Node Version? **v11.15.0**
Snoostorm Version? **1.2.0**

**Comment by kyleratti** [comment]
I'm seeing this too with npm

**Comment by MayorMonty** [comment]
Fixed in the latest patch. I being the complete idiot I am, forgot to build before publishing. I set up a `prepublish` script to build automatically

**Comment by jasonharrison** [comment]
It happens. Thanks @MayorMonty .

**Comment by kyleratti** [comment]
Thanks @anulman!
